berlinonline::webdirectory:           '/srv/www'
berlinonline::repo_tool:              'zypp'
berlinonline::additional_roles:
  - 'berlinonline::systemd'

elasticsearch::es_directory:        '/usr/share/java/elasticsearch'

berlinonline::packagelist:
  avahi:
    name: avahi
  nfs_server:
    name: nfs-kernel-server
  certs:
    name:
      - ca-certificates-cacert
      - ca-certificates-mozilla
  php5-zip: 
    name: php5-zip
    notify: Service[php-fpm]
  php5-zlib: 
    name: php5-zlib
    notify: Service[php-fpm]
  php5-fileinfo:
    name: php5-fileinfo
    notify: Service[php-fpm]
  php5-xdebug:
    name: php5-xdebug
    notify: Service[php-fpm]
    require: Zypprepo[OpenSuse_PHP_Extension]
  php5-openssl:
    name: php5-openssl
    notify: Service[php-fpm]
  php5-intl:
    name: php5-intl
    notify: Service[php-fpm]
  php5-gd:
    name: php5-gd
    notify: Service[php-fpm]
  php5-xsl:
    name: php5-xsl
    notify: Service[php-fpm]
  php5-curl:
    name: php5-curl
    notify: Service[php-fpm]
  php5-json:
    name: php5-json
    notify: Service[php-fpm]
  php5-tokenizer:
    name: php5-tokenizer
    notify: Service[php-fpm]
  php5-iconv:
    name: php5-iconv
    notify: Service[php-fpm]
  php5-phar:
    name: php5-phar
    notify: Service[php-fpm]
  php5-xmlwriter:
    name: php5-xmlwriter
    notify: Service[php-fpm]
  php5-imagick:
    name: php5-imagick
    require: Exec[zypper-refresh]
  npm:
    name: npm
  php5-ctype:
    name: php5-ctype
    notfiy: Service[php-fpm]


php::fpm_service_name:    'php-fpm'
php::fpm_package_name:    'php5-fpm'